<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage, type UploadFile, type UploadInstance } from 'element-plus'
import request from '../utils/request'
import { useBiText, type BiDict } from '../utils/biText'

const d: BiDict = {
  loading: { 'zh-CN': '正在加载配置…', en: 'Loading configuration…' },
  scopeAlert: {
    'zh-CN':
      '配置支付宝开放平台应用与签名密钥。字段可分次填写保存；是否开放支付宝支付由「系统配置 → 收费方式」控制，正式收款前请确保 AppID 与签名密钥齐全。',
    en: 'Configure the Alipay Open Platform app and signing keys. Fields can be saved gradually. Whether Alipay is open is controlled by System Settings → Payment Methods; complete AppID and keys before taking live payments.'
  },
  scope: {
    'zh-CN': '仅超级管理员可修改支付宝支付配置。',
    en: 'Only super administrators can modify the Alipay configuration.'
  },
  sectionApp: { 'zh-CN': '开放平台应用', en: 'Open Platform App' },
  sectionAppHint: {
    'zh-CN': '支付宝开放平台创建的网页/移动应用的唯一标识，缴费与授权均以该应用发起。',
    en: 'The unique ID of the web/mobile app created on the Alipay Open Platform. Both payment and auth are issued by this app.'
  },
  appId: { 'zh-CN': '应用 AppID', en: 'App AppID' },
  appIdPlaceholder: { 'zh-CN': '支付宝应用 AppID（纯数字）', en: 'Alipay app AppID (digits only)' },
  appIdHint: {
    'zh-CN': '在支付宝开放平台“我的应用 → 应用详情”中查看。',
    en: 'Find it under My Apps → App Details on the Alipay Open Platform.'
  },
  sectionKey: { 'zh-CN': '签名密钥（RSA2）', en: 'Signing Keys (RSA2)' },
  sectionKeyHint: {
    'zh-CN': '请求签名使用应用私钥；响应与异步通知验签使用支付宝公钥。两者均从开放平台“开发设置 → 接口加签方式(RSA2)”获取，选择文件后保存，后端自动校验密钥格式；文件内容仅保存不回显。',
    en: 'Requests are signed with the app private key; Alipay responses and async notifications are verified with the Alipay public key. Both come from Dev Settings → Signing Mode (RSA2) on the Open Platform. The backend validates the keys on save. Files are stored but never returned.'
  },
  privateKeyStatus: { 'zh-CN': '应用私钥', en: 'App private key' },
  publicKeyStatus: { 'zh-CN': '支付宝公钥', en: 'Alipay public key' },
  configured: { 'zh-CN': '已配置', en: 'Configured' },
  notConfigured: { 'zh-CN': '未配置', en: 'Not configured' },
  privateKeyFile: { 'zh-CN': '应用私钥文件', en: 'App Private Key File' },
  privateKeyFileHint: {
    'zh-CN': '支付宝密钥工具生成的私钥（PKCS#8 PEM 文本）',
    en: 'Private key generated by the Alipay key tool (PKCS#8 PEM text)'
  },
  privateKeySaveHint: {
    'zh-CN': '选择文件并保存后即替换已存私钥；不选择则保持已存私钥不变。',
    en: 'Pick a file and save to replace the stored private key; leave it empty to keep the existing key.'
  },
  publicKeyFile: { 'zh-CN': '支付宝公钥文件', en: 'Alipay Public Key File' },
  publicKeyFileHint: {
    'zh-CN': '开放平台密钥页复制的支付宝公钥（可保存为 .txt），或带 PUBLIC KEY 头尾的 PEM 文本',
    en: 'The Alipay public key copied from the platform key page (saved as .txt), or PEM text with PUBLIC KEY headers'
  },
  publicKeySaveHint: {
    'zh-CN': '选择文件并保存后即替换已存公钥；不选择则保持已存公钥不变。',
    en: 'Pick a file and save to replace the stored public key; leave it empty to keep the existing key.'
  },
  chooseFile: { 'zh-CN': '选择文件', en: 'Choose file' },
  chooseFileTip: { 'zh-CN': '支持 .pem / .crt / .cer / .txt', en: '.pem / .crt / .cer / .txt supported' },
  fileTypeHint: {
    'zh-CN': '仅支持 .pem / .crt / .cer / .txt 格式的密钥文件',
    en: 'Only .pem / .crt / .cer / .txt key files are supported'
  },
  fileSizeHint: { 'zh-CN': '文件过大，请确认选择的是密钥文本文件', en: 'File too large; please pick a key text file' },
  save: { 'zh-CN': '保存配置', en: 'Save configuration' },
  saving: { 'zh-CN': '保存中…', en: 'Saving…' },
  saved: { 'zh-CN': '配置已保存', en: 'Configuration saved' },
  loadFailed: { 'zh-CN': '加载配置失败，请重试', en: 'Failed to load configuration. Try again.' },
  lastUpdated: { 'zh-CN': '最近更新', en: 'Last updated' },
  sectionNotify: { 'zh-CN': '支付回调地址', en: 'Payment notify URL' },
  sectionNotifyHint: {
    'zh-CN':
      '默认由「系统配置 → 后台基础地址」拼接，可手动修改并保存；也可一键恢复默认。把该地址填到支付宝开放平台应用「开发设置 → 应用网关」，须公网可访问。若默认仍是 localhost，请先在系统配置填写云端公网 HTTPS 域名。验签使用本页支付宝公钥（RSA2）。这不是授权回调地址（OAuth）。',
    en: 'Defaults from System Settings → Admin base URL; you can edit and save, or restore the default in one click. Paste this URL into Alipay Open Platform → App Dev Settings → Application Gateway. It must be publicly reachable. If the default is still localhost, set the public HTTPS origin in System Settings first. Notifications are verified with the Alipay public key (RSA2) on this page. This is not the OAuth redirect URL.'
  },
  notifyUrl: { 'zh-CN': '回调地址', en: 'Notify URL' },
  notifyUrlHint: {
    'zh-CN': '默认由「系统配置 → 后台基础地址」拼接；可手动修改。与默认相同或留空保存后会跟随默认。路径建议为 /api/public/payment/alipay/notify。',
    en: 'Defaults from System Settings → Admin base URL; you can edit it. Saving the default or blank keeps following the default. Preferred path: /api/public/payment/alipay/notify.'
  },
  restoreDefault: { 'zh-CN': '恢复默认', en: 'Restore default' },
  restoredDefault: { 'zh-CN': '已恢复为默认地址，请保存配置', en: 'Restored to default. Save to apply.' },
  copy: { 'zh-CN': '复制', en: 'Copy' },
  copySuccess: { 'zh-CN': '已复制回调地址', en: 'Notify URL copied' },
  copyFailed: { 'zh-CN': '复制失败，请手动选择复制', en: 'Copy failed, please copy it manually' }
}

const { t } = useBiText(d)

interface AlipayConfigView {
  appId: string
  appPrivateKeySet: boolean
  alipayPublicKeySet: boolean
  updatedAt: string
  notifyUrl: string
  defaultNotifyUrl: string
}

type SlotKey = 'privateKey' | 'publicKey'

const loading = ref(true)
const saving = ref(false)

const appId = ref('')
const appPrivateKeySet = ref(false)
const alipayPublicKeySet = ref(false)
const updatedAt = ref('')
const notifyUrl = ref('')
const defaultNotifyUrl = ref('')

/** 待上传文件（每次保存后清空；留空表示不更新该项） */
const chosenFiles = ref<Record<SlotKey, File | null>>({
  privateKey: null,
  publicKey: null
})
const privateKeyUploadRef = ref<UploadInstance>()
const publicKeyUploadRef = ref<UploadInstance>()

const privateKeyConfiguredText = computed(() =>
  appPrivateKeySet.value ? t('configured') : t('notConfigured')
)
const publicKeyConfiguredText = computed(() =>
  alipayPublicKeySet.value ? t('configured') : t('notConfigured')
)

/** 仅保留数字（应用 AppID） */
function restrictDigits(event: Event): void {
  const input = event.target as HTMLInputElement
  input.value = input.value.replace(/\D/g, '')
}

function applyView(view: AlipayConfigView): void {
  appId.value = view.appId
  appPrivateKeySet.value = view.appPrivateKeySet
  alipayPublicKeySet.value = view.alipayPublicKeySet
  updatedAt.value = view.updatedAt
  const effective = (view.notifyUrl ?? '').trim()
  const defaults = (view.defaultNotifyUrl ?? '').trim()
  defaultNotifyUrl.value = defaults
  // 与默认相同则留空，用 placeholder 展示默认，避免长 URL 把输入框撑挤后无法点选编辑
  notifyUrl.value = effective && effective !== defaults ? effective : ''
}

/**
 * 后端返回的本地挂钟时间文本（如 2026-09-07T03:01:02），
 * 该时间在站点时区下解释，因此按纯文本格式化，不经过浏览器本地时区换算。
 */
function formatTime(value?: string): string {
  if (!value) {
    return '-'
  }
  const match = /^(\d{4})-(\d{1,2})-(\d{1,2})[T ](\d{1,2}):(\d{2})/.exec(value)
  if (!match) {
    return value
  }
  const pad = (n: string): string => n.padStart(2, '0')
  return `${match[1]}-${pad(match[2])}-${pad(match[3])} ${pad(match[4])}:${match[5]}`
}

async function loadConfig(): Promise<void> {
  loading.value = true
  try {
    const view = await request.get<never, AlipayConfigView>('/system/alipay/config')
    applyView(view)
  } catch (error) {
    ElMessage.error(error instanceof Error && error.message ? error.message : t('loadFailed'))
  } finally {
    loading.value = false
  }
}

/** 选择文件：校验后缀与大小后暂存，保存时随表单上传 */
function handleSlotChange(slotKey: SlotKey, file: UploadFile): void {
  const raw = file.raw
  if (!raw) {
    return
  }
  const slotUploadRef = uploadRefOf(slotKey)
  if (!/\.(pem|crt|cer|txt)$/i.test(raw.name)) {
    ElMessage.warning(t('fileTypeHint'))
    slotUploadRef?.clearFiles()
    return
  }
  if (raw.size > 512 * 1024) {
    ElMessage.warning(t('fileSizeHint'))
    slotUploadRef?.clearFiles()
    return
  }
  chosenFiles.value[slotKey] = raw
  slotUploadRef?.clearFiles()
}

function removeSlotFile(slotKey: SlotKey): void {
  chosenFiles.value[slotKey] = null
  uploadRefOf(slotKey)?.clearFiles()
}

function uploadRefOf(slotKey: SlotKey): UploadInstance | undefined {
  return slotKey === 'privateKey' ? privateKeyUploadRef.value : publicKeyUploadRef.value
}

function clearChosenFiles(): void {
  chosenFiles.value = { privateKey: null, publicKey: null }
  privateKeyUploadRef.value?.clearFiles()
  publicKeyUploadRef.value?.clearFiles()
}

async function handleSave(): Promise<void> {
  saving.value = true
  try {
    const fd = new FormData()
    fd.append('appId', appId.value.trim())
    fd.append('notifyUrl', notifyUrl.value.trim())
    // 敏感字段留空表示保持不变，由后端处理
    const privateKeyFile = chosenFiles.value.privateKey
    const publicKeyFile = chosenFiles.value.publicKey
    if (privateKeyFile) {
      fd.append('appPrivateKeyFile', privateKeyFile)
    }
    if (publicKeyFile) {
      fd.append('alipayPublicKeyFile', publicKeyFile)
    }
    const view = await request.post<never, AlipayConfigView>('/system/alipay/config', fd)
    applyView(view)
    clearChosenFiles()
    ElMessage.success(t('saved'))
  } catch (error) {
    ElMessage.error(error instanceof Error && error.message ? error.message : t('loadFailed'))
  } finally {
    saving.value = false
  }
}

async function copyNotifyUrl(): Promise<void> {
  const text = (notifyUrl.value.trim() || defaultNotifyUrl.value.trim())
  if (!text) {
    return
  }
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text)
    } else {
      const area = document.createElement('textarea')
      area.value = text
      area.style.position = 'fixed'
      area.style.opacity = '0'
      document.body.appendChild(area)
      area.select()
      document.execCommand('copy')
      document.body.removeChild(area)
    }
    ElMessage.success(t('copySuccess'))
  } catch {
    ElMessage.error(t('copyFailed'))
  }
}

function restoreDefaultNotifyUrl(): void {
  notifyUrl.value = ''
  ElMessage.success(t('restoredDefault'))
}

const notifyIsDefault = computed(
  () => !notifyUrl.value.trim() || notifyUrl.value.trim() === defaultNotifyUrl.value.trim()
)

const effectiveNotifyUrl = computed(
  () => notifyUrl.value.trim() || defaultNotifyUrl.value.trim()
)

onMounted(loadConfig)
</script>

<template>
  <section class="alipay-page">
    <el-card class="panel" shadow="never" v-loading="loading">
      <el-form label-position="top" class="alipay-form" @submit.prevent="handleSave">
        <el-alert type="info" :closable="false" class="scope-alert" show-icon>
          <span>{{ t('scopeAlert') }}</span>
        </el-alert>
        <el-alert type="warning" :closable="false" class="scope-alert" show-icon>
          <span>{{ t('scope') }}</span>
        </el-alert>

        <h3 class="group-title">{{ t('sectionNotify') }}</h3>
        <p class="section-hint">{{ t('sectionNotifyHint') }}</p>
        <el-form-item :label="t('notifyUrl')" class="notify-item">
          <el-input
            v-model="notifyUrl"
            clearable
            class="field notify-field"
            :placeholder="defaultNotifyUrl || t('notifyUrl')"
          />
          <div class="notify-actions">
            <el-button native-type="button" :disabled="!effectiveNotifyUrl" @click="copyNotifyUrl">
              {{ t('copy') }}
            </el-button>
            <el-button
              native-type="button"
              :disabled="!defaultNotifyUrl || notifyIsDefault"
              @click="restoreDefaultNotifyUrl"
            >
              {{ t('restoreDefault') }}
            </el-button>
          </div>
          <div class="field-hint">{{ t('notifyUrlHint') }}</div>
        </el-form-item>

        <el-divider />

        <h3 class="group-title">{{ t('sectionApp') }}</h3>
        <p class="section-hint">{{ t('sectionAppHint') }}</p>
        <el-form-item :label="t('appId')">
          <el-input
            v-model="appId"
            :placeholder="t('appIdPlaceholder')"
            maxlength="32"
            clearable
            class="field"
            @input="restrictDigits"
          />
          <div class="field-hint">{{ t('appIdHint') }}</div>
        </el-form-item>

        <el-divider />

        <h3 class="group-title">{{ t('sectionKey') }}</h3>
        <p class="section-hint">{{ t('sectionKeyHint') }}</p>

        <div class="status-row">
          <el-tag size="small" :type="appPrivateKeySet ? 'success' : 'info'" effect="plain">
            {{ t('privateKeyStatus') }}：{{ privateKeyConfiguredText }}
          </el-tag>
          <el-tag size="small" :type="alipayPublicKeySet ? 'success' : 'info'" effect="plain">
            {{ t('publicKeyStatus') }}：{{ publicKeyConfiguredText }}
          </el-tag>
        </div>

        <div class="field-grid">
          <el-form-item :label="t('privateKeyFile')">
            <el-upload
              ref="privateKeyUploadRef"
              :auto-upload="false"
              :show-file-list="false"
              accept=".pem,.crt,.cer,.txt"
              class="upload-slot"
              :on-change="(f: UploadFile) => handleSlotChange('privateKey', f)"
            >
              <div class="upload-trigger">
                <el-tag
                  v-if="chosenFiles.privateKey"
                  closable
                  class="file-tag"
                  @close="removeSlotFile('privateKey')"
                >
                  {{ chosenFiles.privateKey.name }}
                </el-tag>
                <template v-else>
                  <span class="choose-text">{{ t('chooseFile') }}</span>
                  <span class="choose-tip">{{ t('chooseFileTip') }}</span>
                </template>
              </div>
            </el-upload>
            <div class="field-hint">{{ t('privateKeyFileHint') }}</div>
            <div class="field-hint">{{ t('privateKeySaveHint') }}</div>
          </el-form-item>
          <el-form-item :label="t('publicKeyFile')">
            <el-upload
              ref="publicKeyUploadRef"
              :auto-upload="false"
              :show-file-list="false"
              accept=".pem,.crt,.cer,.txt"
              class="upload-slot"
              :on-change="(f: UploadFile) => handleSlotChange('publicKey', f)"
            >
              <div class="upload-trigger">
                <el-tag
                  v-if="chosenFiles.publicKey"
                  closable
                  class="file-tag"
                  @close="removeSlotFile('publicKey')"
                >
                  {{ chosenFiles.publicKey.name }}
                </el-tag>
                <template v-else>
                  <span class="choose-text">{{ t('chooseFile') }}</span>
                  <span class="choose-tip">{{ t('chooseFileTip') }}</span>
                </template>
              </div>
            </el-upload>
            <div class="field-hint">{{ t('publicKeyFileHint') }}</div>
            <div class="field-hint">{{ t('publicKeySaveHint') }}</div>
          </el-form-item>
        </div>

        <div class="form-footer">
          <div class="footer-meta">
            <span v-if="updatedAt" class="meta">
              {{ t('lastUpdated') }}: {{ formatTime(updatedAt) }}
            </span>
          </div>
          <el-button type="primary" :loading="saving" native-type="submit">
            {{ saving ? t('saving') : t('save') }}
          </el-button>
        </div>
      </el-form>
    </el-card>
  </section>
</template>

<style scoped>
.alipay-page {
  animation: fade-up 0.45s cubic-bezier(0.22, 1, 0.36, 1) both;
}

.panel {
  border-radius: var(--fp-radius);
  box-shadow: var(--fp-shadow-soft);
}

.alipay-form {
  max-width: 860px;
}

.scope-alert {
  margin-bottom: 12px;
}

.group-title {
  margin: 6px 0 14px;
  font-size: 1rem;
}

.section-hint {
  margin: -6px 0 14px;
  font-size: 0.8rem;
  line-height: 1.6;
  color: var(--fp-muted);
}

.status-row {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-bottom: 14px;
}

.field-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 0 20px;
}

.field {
  width: 100%;
}

.notify-item :deep(.el-form-item__content) {
  display: flex;
  flex-direction: column;
  align-items: stretch;
  gap: 8px;
}

.notify-field {
  width: 100%;
}

.notify-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.notify-field :deep(.el-input__inner) {
  font-family: ui-monospace, SFMono-Regular, Consolas, 'Liberation Mono', Menlo, monospace;
  font-size: 0.82rem;
}

.upload-slot {
  width: 100%;
}

.upload-trigger {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 2px;
  min-height: 76px;
  padding: 10px 12px;
  border: 1px dashed var(--el-border-color, #dcdfe6);
  border-radius: var(--fp-radius, 6px);
  background: var(--fp-surface-soft, rgba(0, 0, 0, 0.02));
  cursor: pointer;
  transition: border-color 0.2s ease, background-color 0.2s ease;
  box-sizing: border-box;
}

.upload-slot :deep(.el-upload),
.upload-slot :deep(.el-upload-dragger) {
  width: 100%;
}

.upload-trigger:hover {
  border-color: var(--el-color-primary, #409eff);
  background: var(--fp-surface-soft-hover, rgba(0, 0, 0, 0.04));
}

.upload-trigger .el-tag.file-tag {
  max-width: 100%;
}

.file-tag :deep(.el-tag__content) {
  max-width: 320px;
  overflow: hidden;
  text-overflow: ellipsis;
}

.choose-text {
  font-size: 0.85rem;
  color: var(--el-color-primary, #409eff);
}

.choose-tip {
  font-size: 0.74rem;
  color: var(--fp-muted);
}

.field-hint {
  margin-top: 6px;
  font-size: 0.78rem;
  line-height: 1.5;
  color: var(--fp-muted);
}

.form-footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  flex-wrap: wrap;
  margin-top: 8px;
  padding-top: 16px;
  border-top: 1px dashed var(--el-border-color-light, #e4e7ed);
}

.meta {
  font-size: 0.8rem;
  color: var(--fp-muted);
}

@keyframes fade-up {
  from {
    opacity: 0;
    transform: translateY(10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@media (max-width: 640px) {
  .field-grid {
    grid-template-columns: 1fr;
  }
}
</style>
