<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage, ElMessageBox, type FormInstance, type FormRules } from 'element-plus'
import request from '../utils/request'
import { useBiText, type BiDict } from '../utils/biText'
import { useUserStore } from '../stores/user'

const d: BiDict = {
  pageHint: {
    'zh-CN':
      '管理边缘节点及其与车场的归属关系。节点可管辖 0..N 个车场（单一车场即 1:1 特例）；绑定关系随配置同步自动下发到边缘侧，云端无需逐个推送车场。',
    en: 'Manage edge nodes and their lots. A node may manage 0..N lots (1:1 is the single-lot case); bindings are pushed to each node automatically with the config sync.'
  },
  refresh: { 'zh-CN': '刷新', en: 'Refresh' },
  add: { 'zh-CN': '新增节点', en: 'Add node' },
  colCode: { 'zh-CN': '节点编号', en: 'Node code' },
  colName: { 'zh-CN': '节点名称', en: 'Node name' },
  colLots: { 'zh-CN': '管辖车场', en: 'Managed lots' },
  colStatus: { 'zh-CN': '状态', en: 'Status' },
  colRemark: { 'zh-CN': '备注', en: 'Remark' },
  colCreatedAt: { 'zh-CN': '创建时间', en: 'Created at' },
  colActions: { 'zh-CN': '操作', en: 'Actions' },
  enabled: { 'zh-CN': '启用', en: 'Enabled' },
  disabled: { 'zh-CN': '停用', en: 'Disabled' },
  edit: { 'zh-CN': '编辑', en: 'Edit' },
  bindLots: { 'zh-CN': '绑定车场', en: 'Bind lots' },
  delete: { 'zh-CN': '删除', en: 'Delete' },
  expandHint: { 'zh-CN': '展开查看名下车场', en: 'Expand to view lots' },
  noLots: { 'zh-CN': '未绑定车场', en: 'No lots bound' },
  boundLotTag: { 'zh-CN': '已绑定', en: 'Bound' },
  emptyList: { 'zh-CN': '暂无边缘节点', en: 'No edge nodes yet' },
  emptyHint: {
    'zh-CN': '创建边缘节点并在其上绑定车场后，配置同步会按节点整体下发。',
    en: 'Create a node and bind lots; the config sync will push them per node.'
  },
  deleteConfirmNone: { 'zh-CN': '确定删除节点“{name}”吗？', en: 'Delete node "{name}"?' },
  deleteConfirmSome: {
    'zh-CN': '节点“{name}”名下绑定了 {count} 个车场，删除后这些车场将被解绑（车场本身不受影响）。确定删除吗？',
    en: 'Node "{name}" manages {count} lot(s). Deleting it unbinds those lots (lots themselves are kept). Delete?'
  },
  deleteSuccess: { 'zh-CN': '节点已删除', en: 'Node deleted' },
  createSuccess: { 'zh-CN': '节点已创建', en: 'Node created' },
  updateSuccess: { 'zh-CN': '已保存', en: 'Saved' },
  bindSuccess: { 'zh-CN': '绑定已更新', en: 'Binding updated' },
  dialogCreateTitle: { 'zh-CN': '新增边缘节点', en: 'New Edge Node' },
  dialogEditTitle: { 'zh-CN': '编辑边缘节点', en: 'Edit Edge Node' },
  fieldCode: { 'zh-CN': '节点编号', en: 'Node code' },
  fieldName: { 'zh-CN': '节点名称', en: 'Node name' },
  fieldEnabled: { 'zh-CN': '启用', en: 'Enabled' },
  fieldRemark: { 'zh-CN': '备注', en: 'Remark' },
  codeAutoHint: {
    'zh-CN': '由云端按 FreePark + 年月日 + 6 位随机数自动生成，创建后不可修改。',
    en: 'Auto-generated by the cloud as FreePark + date + 6 random digits. It cannot be changed after creation.'
  },
  namePlaceholder: { 'zh-CN': '如 杭州一号边缘盒子', en: 'e.g. Hangzhou box #1' },
  remarkPlaceholder: { 'zh-CN': '选填，最长 255 字符', en: 'Optional, up to 255 chars' },
  nameRequired: { 'zh-CN': '请输入节点名称', en: 'Node name is required' },
  confirm: { 'zh-CN': '确定', en: 'Confirm' },
  cancel: { 'zh-CN': '取消', en: 'Cancel' },
  save: { 'zh-CN': '保存', en: 'Save' },
  bindDialogTitle: { 'zh-CN': '绑定车场', en: 'Bind lots' },
  bindDialogSub: {
    'zh-CN': '节点：{name}（{code}）',
    en: 'Node: {name} ({code})'
  },
  bindHint: {
    'zh-CN':
      '车场只能归属一个节点。勾选属于其他节点的车场会将其转移至本节点；取消勾选当前已绑定的车场会将其解绑。',
    en: 'A lot can only belong to one node. Checking a lot owned by another node moves it here; unchecking moves it away.'
  },
  lotSearch: { 'zh-CN': '搜索车场名称/编码', en: 'Search by lot name/code' },
  boundHere: { 'zh-CN': '本节点', en: 'This node' },
  ownerLabel: { 'zh-CN': '归属 {name}', en: 'Owned by {name}' },
  freeLot: { 'zh-CN': '未绑定', en: 'Unbound' },
  noLotOptions: { 'zh-CN': '暂无可用车场', en: 'No lots available' },
  noLotOptionsHint: {
    'zh-CN': '请先在「车场管理」中创建车场，再回来绑定。',
    en: 'Create lots under Lot Management first, then bind them here.'
  },
  gotoLots: { 'zh-CN': '前往车场管理', en: 'Go to lot management' },
  selectedCount: { 'zh-CN': '已选 {count} 个车场', en: '{count} selected' },
  noAccessTitle: { 'zh-CN': '需要超级管理员权限', en: 'Super admin required' },
  noAccessDesc: {
    'zh-CN': '边缘节点管理仅超级管理员可操作，请联系超级管理员。',
    en: 'Edge node management is restricted to super admins.'
  },
  backToHome: { 'zh-CN': '返回首页', en: 'Back to home' }
}

const { t } = useBiText(d)
const router = useRouter()
const userStore = useUserStore()

/** 仅超级管理员可管理边缘节点 */
const forbidden = computed(() => !userStore.isSuperAdmin)

interface BoundLot {
  parkCode: string
  parkName: string
}

interface EdgeNodeItem {
  id: number
  code: string
  name: string
  enabled: boolean
  remark: string | null
  createdAt: string
  updatedAt: string
  boundLots: BoundLot[]
}

interface LotItem {
  code: string
  name: string
}

const loading = ref(false)
const rows = ref<EdgeNodeItem[]>([])
const allLots = ref<LotItem[]>([])

async function loadList() {
  loading.value = true
  try {
    rows.value = await request.get<never, EdgeNodeItem[]>('/system/edge-nodes')
  } catch (error) {
    ElMessage.error(error instanceof Error && error.message ? error.message : t('refresh'))
  } finally {
    loading.value = false
  }
}

async function loadAllLots() {
  try {
    const data = await request.get<never, LotItem[]>('/lots')
    allLots.value = [...data].sort((a, b) => a.code.localeCompare(b.code))
  } catch (error) {
    allLots.value = []
    ElMessage.error(error instanceof Error && error.message ? error.message : t('refresh'))
  }
}

function formatTime(value?: string): string {
  if (!value) {
    return '-'
  }
  const match = /^(\d{4})-(\d{1,2})-(\d{1,2})[T ](\d{1,2}):(\d{2})/.exec(value)
  if (!match) {
    return value
  }
  const pad = (n: string): string => n.padStart(2, '0')
  return `${match[1]}-${pad(match[2])}-${pad(match[3])} ${pad(match[4])}:${match[5]}`
}

/* ---------------- 新增 / 编辑 ---------------- */

const editorVisible = ref(false)
const editorIsCreate = ref(true)
const editingId = ref<number | null>(null)
const saving = ref(false)
const formRef = ref<FormInstance>()
const form = reactive({
  code: '',
  name: '',
  enabled: true,
  remark: ''
})

const formRules = computed<FormRules>(() => ({
  name: [{ required: true, message: t('nameRequired'), trigger: 'blur' }]
}))

function openCreateDialog() {
  editorIsCreate.value = true
  editingId.value = null
  form.code = ''
  form.name = ''
  form.enabled = true
  form.remark = ''
  editorVisible.value = true
}

function openEditDialog(row: EdgeNodeItem) {
  editorIsCreate.value = false
  editingId.value = row.id
  form.code = row.code
  form.name = row.name
  form.enabled = row.enabled
  form.remark = row.remark ?? ''
  editorVisible.value = true
}

async function saveEditor() {
  try {
    await formRef.value?.validate()
  } catch {
    return
  }
  saving.value = true
  try {
    if (editorIsCreate.value) {
      // 节点编号由云端自动生成，新增时无需（也不可）提交
      await request.post<never, EdgeNodeItem>('/system/edge-nodes', {
        name: form.name.trim(),
        enabled: form.enabled,
        remark: form.remark.trim() || undefined
      })
      ElMessage.success(t('createSuccess'))
    } else {
      await request.put<never, EdgeNodeItem>(`/system/edge-nodes/${editingId.value}`, {
        name: form.name.trim(),
        enabled: form.enabled,
        remark: form.remark.trim() || undefined
      })
      ElMessage.success(t('updateSuccess'))
    }
    editorVisible.value = false
    loadList()
  } catch (error) {
    ElMessage.error(error instanceof Error && error.message ? error.message : t('refresh'))
  } finally {
    saving.value = false
  }
}

/* ---------------- 删除 ---------------- */

async function deleteNode(row: EdgeNodeItem) {
  const confirmText =
    row.boundLots.length === 0
      ? t('deleteConfirmNone').replace('{name}', row.name)
      : t('deleteConfirmSome')
          .replace('{name}', row.name)
          .replace('{count}', String(row.boundLots.length))
  try {
    await ElMessageBox.confirm(confirmText, '', {
      type: 'warning',
      confirmButtonText: t('confirm'),
      cancelButtonText: t('cancel')
    })
  } catch {
    return
  }
  try {
    await request.delete<never, void>(`/system/edge-nodes/${row.id}`)
    ElMessage.success(t('deleteSuccess'))
    loadList()
  } catch (error) {
    ElMessage.error(error instanceof Error && error.message ? error.message : t('refresh'))
  }
}

/* ---------------- 绑定车场 ---------------- */

const bindVisible = ref(false)
const bindTarget = ref<EdgeNodeItem | null>(null)
const selectedCodes = ref<string[]>([])
const bindKeyword = ref('')
const bindSaving = ref(false)

function openBindDialog(row: EdgeNodeItem) {
  bindTarget.value = row
  bindKeyword.value = ''
  selectedCodes.value = row.boundLots.map((lot) => lot.parkCode)
  bindVisible.value = true
  void loadAllLots()
}

function closeBindDialog() {
  bindVisible.value = false
  bindTarget.value = null
}

const filteredLots = computed<LotItem[]>(() => {
  const kw = bindKeyword.value.trim().toLowerCase()
  if (!kw) {
    return allLots.value
  }
  return allLots.value.filter(
    (lot) =>
      lot.name.toLowerCase().includes(kw) || lot.code.toLowerCase().includes(kw)
  )
})

/** 某车场当前的归属节点名称（不含正在编辑的目标节点），null 表示未绑定或其他情况 */
function ownerNameOf(lotCode: string): string | null {
  const target = bindTarget.value
  if (!target) {
    return null
  }
  for (const node of rows.value) {
    if (node.id === target.id) {
      continue
    }
    if (node.boundLots.some((lot) => lot.parkCode === lotCode)) {
      return node.name
    }
  }
  return null
}

function isBoundHere(lotCode: string): boolean {
  const target = bindTarget.value
  return target ? target.boundLots.some((lot) => lot.parkCode === lotCode) : false
}

function lotMeta(lotCode: string): { type: 'here' | 'other' | 'free'; label: string } {
  if (isBoundHere(lotCode)) {
    return { type: 'here', label: t('boundHere') }
  }
  const owner = ownerNameOf(lotCode)
  if (owner) {
    return { type: 'other', label: t('ownerLabel').replace('{name}', owner) }
  }
  return { type: 'free', label: t('freeLot') }
}

async function saveBind() {
  const target = bindTarget.value
  if (!target) {
    return
  }
  bindSaving.value = true
  try {
    await request.put<never, EdgeNodeItem>(`/system/edge-nodes/${target.id}/lots`, {
      parkCodes: selectedCodes.value
    })
    ElMessage.success(t('bindSuccess'))
    closeBindDialog()
    loadList()
  } catch (error) {
    ElMessage.error(error instanceof Error && error.message ? error.message : t('refresh'))
  } finally {
    bindSaving.value = false
  }
}

onMounted(loadList)
</script>

<template>
  <section class="edge-nodes">
    <div v-if="forbidden" class="no-access">
      <div class="no-access-icon">!</div>
      <h3>{{ t('noAccessTitle') }}</h3>
      <p>{{ t('noAccessDesc') }}</p>
      <el-button type="primary" @click="router.push('/')">{{ t('backToHome') }}</el-button>
    </div>

    <template v-else>
      <el-card class="panel" shadow="never">
        <div class="panel-head">
          <span>{{ t('pageHint') }}</span>
          <div class="head-actions">
            <el-button :loading="loading" @click="loadList">{{ t('refresh') }}</el-button>
            <el-button type="primary" @click="openCreateDialog">{{ t('add') }}</el-button>
          </div>
        </div>

        <el-table v-loading="loading" :data="rows" stripe>
          <el-table-column type="expand">
            <template #default="{ row }">
              <div class="expand-wrap">
                <template v-if="(row as EdgeNodeItem).boundLots.length">
                  <span class="lot-chip-group">
                    <el-tag
                      v-for="lot in (row as EdgeNodeItem).boundLots"
                      :key="lot.parkCode"
                      type="primary"
                      effect="plain"
                      class="lot-chip"
                    >
                      {{ lot.parkName }}（{{ lot.parkCode }}）
                    </el-tag>
                  </span>
                </template>
                <span v-else class="no-lots">{{ t('noLots') }}</span>
              </div>
            </template>
          </el-table-column>
          <el-table-column prop="code" :label="t('colCode')" min-width="140" />
          <el-table-column prop="name" :label="t('colName')" min-width="150" />
          <el-table-column :label="t('colStatus')" width="100">
            <template #default="{ row }">
              <el-tag
                :type="(row as EdgeNodeItem).enabled ? 'success' : 'info'"
                effect="light"
                round
              >
                {{ (row as EdgeNodeItem).enabled ? t('enabled') : t('disabled') }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column :label="t('colLots')" width="110">
            <template #default="{ row }">
              <el-tooltip :content="t('expandHint')" placement="top">
                <el-link type="primary" :underline="false">
                  {{ (row as EdgeNodeItem).boundLots.length }}
                </el-link>
              </el-tooltip>
            </template>
          </el-table-column>
          <el-table-column prop="remark" :label="t('colRemark')" min-width="150" show-overflow-tooltip>
            <template #default="{ row }">{{ (row as EdgeNodeItem).remark || '—' }}</template>
          </el-table-column>
          <el-table-column :label="t('colCreatedAt')" min-width="170">
            <template #default="{ row }">{{ formatTime((row as EdgeNodeItem).createdAt) }}</template>
          </el-table-column>
          <el-table-column :label="t('colActions')" width="220" fixed="right">
            <template #default="{ row }">
              <el-button link type="primary" @click="openEditDialog(row as EdgeNodeItem)">
                {{ t('edit') }}
              </el-button>
              <el-button link type="primary" @click="openBindDialog(row as EdgeNodeItem)">
                {{ t('bindLots') }}
              </el-button>
              <el-button link type="danger" @click="deleteNode(row as EdgeNodeItem)">
                {{ t('delete') }}
              </el-button>
            </template>
          </el-table-column>

          <template #empty>
            <el-empty :description="t('emptyList')" :image-size="80">
              <p class="empty-hint">{{ t('emptyHint') }}</p>
            </el-empty>
          </template>
        </el-table>
      </el-card>

      <!-- 新增 / 编辑弹层 -->
      <el-dialog
        v-model="editorVisible"
        :title="editorIsCreate ? t('dialogCreateTitle') : t('dialogEditTitle')"
        width="min(480px, 92vw)"
        destroy-on-close
        append-to-body
      >
        <el-form ref="formRef" :model="form" :rules="formRules" label-width="90px">
          <!-- 编号：新增时自动生成、编辑时只读展示，均不可手工修改 -->
          <el-form-item v-if="!editorIsCreate" :label="t('fieldCode')">
            <el-input :model-value="form.code" disabled />
          </el-form-item>
          <el-form-item v-else :label="t('fieldCode')">
            <div class="auto-code-hint">{{ t('codeAutoHint') }}</div>
          </el-form-item>
          <el-form-item :label="t('fieldName')" prop="name">
            <el-input v-model="form.name" :placeholder="t('namePlaceholder')" maxlength="120" />
          </el-form-item>
          <el-form-item :label="t('fieldEnabled')">
            <el-switch v-model="form.enabled" inline-prompt :active-text="t('enabled')" :inactive-text="t('disabled')" />
          </el-form-item>
          <el-form-item :label="t('fieldRemark')">
            <el-input
              v-model="form.remark"
              type="textarea"
              :rows="2"
              :placeholder="t('remarkPlaceholder')"
              maxlength="255"
              show-word-limit
            />
          </el-form-item>
        </el-form>
        <template #footer>
          <el-button @click="editorVisible = false">{{ t('cancel') }}</el-button>
          <el-button type="primary" :loading="saving" @click="saveEditor">{{ t('save') }}</el-button>
        </template>
      </el-dialog>

      <!-- 绑定车场弹层 -->
      <el-dialog
        v-model="bindVisible"
        :title="t('bindDialogTitle')"
        width="min(620px, 94vw)"
        destroy-on-close
        append-to-body
        @closed="closeBindDialog"
      >
        <template v-if="bindTarget">
          <p class="bind-sub">
            {{ t('bindDialogSub').replace('{name}', bindTarget.name).replace('{code}', bindTarget.code) }}
          </p>
          <el-alert type="info" :closable="false" show-icon class="bind-hint">
            <p class="bind-hint-text">{{ t('bindHint') }}</p>
          </el-alert>

          <template v-if="allLots.length">
            <el-input
              v-model="bindKeyword"
              class="lot-search"
              :placeholder="t('lotSearch')"
              clearable
            />
            <div class="lot-picker">
              <el-checkbox-group v-model="selectedCodes">
                <div v-for="lot in filteredLots" :key="lot.code" class="lot-row">
                  <el-checkbox :value="lot.code">
                    <span class="lot-name">{{ lot.name }}</span>
                    <span class="lot-code">{{ lot.code }}</span>
                    <el-tag
                      size="small"
                      :type="lotMeta(lot.code).type === 'here' ? 'primary' : lotMeta(lot.code).type === 'other' ? 'warning' : 'info'"
                      effect="light"
                      round
                      class="lot-tag"
                    >
                      {{ lotMeta(lot.code).label }}
                    </el-tag>
                  </el-checkbox>
                </div>
              </el-checkbox-group>
              <div v-if="!filteredLots.length" class="picker-empty">
                <el-empty :description="t('noLotOptions')" :image-size="60" />
              </div>
            </div>
            <p class="bind-count">{{ t('selectedCount').replace('{count}', String(selectedCodes.length)) }}</p>
          </template>
          <el-empty v-else :description="t('noLotOptions')" :image-size="70">
            <p class="empty-hint">{{ t('noLotOptionsHint') }}</p>
            <el-button type="primary" plain size="small" @click="router.push('/lots')">
              {{ t('gotoLots') }}
            </el-button>
          </el-empty>
        </template>
        <template #footer>
          <el-button @click="bindVisible = false">{{ t('cancel') }}</el-button>
          <el-button type="primary" :loading="bindSaving" @click="saveBind">{{ t('save') }}</el-button>
        </template>
      </el-dialog>
    </template>
  </section>
</template>

<style scoped>
.edge-nodes {
  animation: fade-in 0.35s ease;
}

.no-access {
  max-width: 560px;
  margin: 8vh auto 0;
  padding: 48px 32px;
  text-align: center;
  border: 1px solid var(--fp-line);
  border-radius: var(--fp-radius);
  background: var(--fp-surface-elevated);
}

.no-access-icon {
  width: 56px;
  height: 56px;
  margin: 0 auto 16px;
  display: grid;
  place-items: center;
  font-size: 1.6rem;
  font-weight: 700;
  color: var(--fp-amber);
  border-radius: 50%;
  background: var(--fp-amber-soft);
}

.no-access h3 {
  margin: 0 0 8px;
  font-family: var(--fp-font-display);
  font-size: 1.1rem;
  color: var(--fp-ink);
}

.no-access p {
  margin: 0 0 22px;
  line-height: 1.65;
  color: var(--fp-muted);
}

.panel {
  border: 1px solid var(--fp-line);
  border-radius: var(--fp-radius);
  background: var(--fp-surface-elevated);
}

.panel-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  margin-bottom: 16px;
  font-size: 0.85rem;
  color: var(--fp-muted);
  line-height: 1.6;
}

.head-actions {
  display: flex;
  align-items: center;
  gap: 10px;
  flex-shrink: 0;
}

.expand-wrap {
  padding: 8px 24px 12px 48px;
}

.lot-chip-group {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.lot-chip {
  max-width: 320px;
}

.no-lots {
  color: var(--fp-muted);
  font-size: 0.85rem;
}

.empty-hint {
  margin: 6px 0 0;
  font-size: 0.8rem;
  color: var(--fp-muted);
}

.bind-sub {
  margin: 0 0 10px;
  font-weight: 600;
  color: var(--fp-ink);
}

.auto-code-hint {
  display: flex;
  align-items: center;
  align-self: stretch;
  min-height: 32px;
  padding: 0 4px;
  font-size: 0.85rem;
  color: var(--fp-muted);
  line-height: 1.5;
}

.bind-hint {
  margin-bottom: 12px;
}

.bind-hint-text {
  margin: 0;
  line-height: 1.6;
}

.lot-search {
  margin-bottom: 10px;
}

.lot-picker {
  max-height: 300px;
  overflow-y: auto;
  border: 1px solid var(--fp-line);
  border-radius: var(--fp-radius-sm);
  padding: 4px 8px;
}

.lot-row {
  display: flex;
  align-items: center;
  padding: 6px 4px;
}

.lot-row + .lot-row {
  border-top: 1px dashed var(--fp-line);
}

.lot-name {
  font-weight: 500;
  color: var(--fp-ink);
  margin-right: 8px;
}

.lot-code {
  font-family: var(--fp-font-mono, Consolas, monospace);
  font-size: 0.82rem;
  color: var(--fp-muted);
  margin-right: 8px;
}

.lot-tag {
  margin-left: auto;
}

.picker-empty {
  padding: 8px 0;
}

.bind-count {
  margin: 10px 0 0;
  font-size: 0.8rem;
  color: var(--fp-muted);
  text-align: right;
}

@keyframes fade-in {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
</style>
